name: Deploy Function

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_STAGING }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Debug Supabase CLI Version
        run: supabase --version

      - name: Use Supavisor for IPv4
        run: |
          export PGOPTIONS='--client-min-messages=warning'
          export PGSSLMODE=require
          export SUPABASE_DB_HOST="aws-0-[aws-region].pooler.supabase.com"
          export SUPABASE_DB_PORT="6543"  # Supavisor 사용
          supabase link --project-ref $SUPABASE_PROJECT_ID --debug

      - name: Push Database Changes
        run: supabase db push
