name: Deploy to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_STAGING }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Debug Supabase CLI Version
        run: supabase --version

      - name: Debug Supabase ENV Variables
        run: |
          echo "SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID_STAGING }}"
          echo "SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}"
          echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN_STAGING }}"

      - name: Enable IPv4 for Supabase Link
        run: |
          export PGOPTIONS='--client-min-messages=warning'
          export PGSSLMODE=require
          export SUPABASE_DB_HOST="db.${{ secrets.SUPABASE_PROJECT_ID_STAGING }}.supabase.co"
          export PGHOST="$(getent ahostsv4 db.${{ secrets.SUPABASE_PROJECT_ID_STAGING }}.supabase.co | awk '{print $1; exit}')"
          export PGPORT="5432"
          supabase link --project-ref $SUPABASE_PROJECT_ID --debug

      - name: Remove Old Supabase Config
        run: rm -rf ~/.supabase

      - name: Deploy Database Changes
        run: supabase db push
